version: 2

updates:
  - directory: "/"
    open-pull-requests-limit: 5
    package-ecosystem: "pip"
    rebase-strategy: auto
    allow:
      - dependency-type: "direct"
    schedule:
      interval: "weekly"
