version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: "/"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    allow:
      - dependency-type: direct
    schedule:
      interval: weekly
