- name: breaking
  description: Breaking Changes
  color: bfd4f2

- name: bug
  description: Something isn't working
  color: d73a4a

- name: build
  description: Build System and Dependencies
  color: bfdadc

- name: ci
  description: Continuous Integration
  color: 4a97d6

- name: dependencies
  description: Pull requests that update a dependency file
  color: 0366d6

- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca

- name: enhancement
  description: New feature or request
  color: a2eeef

- name: good first issue
  description: Good for newcomers
  color: 7057ff

- name: performance
  description: Performance
  color: "016175"

- name: question
  description: Further information is requested
  color: d876e3

- name: refactoring
  description: Refactoring
  color: ef67c4

- name: removal
  description: Removals and Deprecations
  color: 9ae7ea

- name: style
  description: Style
  color: c120e5

- name: testing
  description: Testing
  color: b1fc6f
