# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.30.2.dev11+gcc4e4ac.d20220502'
version_tuple = (0, 30, 2, 'dev11', 'gcc4e4ac.d20220502')
